apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-api
          image: chichia/todo-myapp:latest
          ports:
            - containerPort: 8291
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8291
#            initialDelaySeconds: 5
#            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8291
#            initialDelaySeconds: 30
#            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SERVER_PORT
              value: "8291"
