#services:
#  localstack:
#    image: localstack/localstack
#    container_name: localstack
#    ports:
#      - "4566:4566"  # LocalStack services
#      - "4571:4571"
#    environment:
#      - SERVICES=s3,iam,ec2
#      - DEBUG=1
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - "./.localstack:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#
#  springboot-app:
#    build:
#      context: ./app/
#      dockerfile: Dockerfile
#    container_name:
#    ports:
#      - "8080:8080"
#    depends_on:
#      - localstack


#services:
#  localstack:
#    image: localstack/localstack
#    container_name: localstack
#    ports:
#      - "4566:4566"
#      - "4571:4571"
#    environment:
#      - SERVICES=s3,iam,ec2
#      - DEBUG=1
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - "./.localstack:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#
#  springboot-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name:
#    ports:
#      - "8291:8291"
#    depends_on:
#      - localstack


services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,iam,ec2
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mytodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-springboot
    ports:
      - "8291:8291"
    depends_on:
      - localstack
      - postgres

volumes:
  pg_data:
